version: '3.0'

services:
  bazel:
    image: tradingai/bazel:latest
    command:
      /bin/bash /go/src/github.com/tradingAI/go/docker-compose.sh
    volumes:
      - .:/go/src/github.com/tradingAI/go
